/**
 * Application registration codes (brief §12).
 *
 * The client hinted the code "may relate to how long the applicant has been
 * with the ministry" but has not defined the rule. Rather than guess at
 * semantics that would then be baked into every stored code, the MVP issues a
 * code that is:
 *
 *   - unique and collision-resistant,
 *   - readable aloud over the phone,
 *   - unambiguous (no O/0, I/1, S/5 confusion),
 *   - and generated by ONE function, so the format can be redefined later
 *     without touching any screen or service.
 *
 * Historical codes are never regenerated — they are stored on the application
 * row. Changing the format here only affects codes issued from that point on.
 */
import * as Crypto from 'expo-crypto';

/**
 * Deliberately excludes 0/O, 1/I/L, 5/S, 2/Z and 8/B so a code read over a
 * phone line cannot be mis-transcribed.
 */
const UNAMBIGUOUS_ALPHABET = '34679ACDEFGHJKMNPQRTUVWXY';

export interface RegistrationCodeFormat {
  /** Fixed leading segment. */
  prefix: string;
  /** Included so codes remain sortable and obviously belong to a cycle. */
  includeYear: boolean;
  /** Number of random characters in the final segment. */
  randomLength: number;
  /** Separator between segments. */
  separator: string;
}

export const REGISTRATION_CODE_FORMAT: RegistrationCodeFormat = {
  prefix: 'ZWCC',
  includeYear: true,
  randomLength: 6,
  separator: '-',
};

/**
 * Context handed to the generator. Nothing currently uses `membershipTenure`,
 * but it is threaded through so the client's "length of time with the ministry"
 * rule can be implemented here alone when it is defined.
 */
export interface RegistrationCodeContext {
  programYear: number;
  /** e.g. 'under_1' | '1_3' | '3_5' | '5_10' | 'over_10' — see form config. */
  membershipTenure?: string | null;
  isMember?: boolean;
}

function randomSegment(length: number): string {
  // expo-crypto is backed by the platform CSPRNG. Math.random() would be
  // predictable, and these codes are quoted as a verification factor.
  const bytes = Crypto.getRandomBytes(length);
  let out = '';
  for (let i = 0; i < length; i += 1) {
    // `bytes` is guaranteed to be `length` long; the non-null assertion keeps
    // noUncheckedIndexedAccess happy without a runtime branch per character.
    const byte = bytes[i] as number;
    out += UNAMBIGUOUS_ALPHABET[byte % UNAMBIGUOUS_ALPHABET.length];
  }
  return out;
}

/**
 * The single place a registration code is created.
 *
 * Uniqueness is additionally guaranteed by a UNIQUE constraint on
 * `applications.registration_code`; the service retries on the (vanishingly
 * unlikely) collision.
 */
export function generateRegistrationCode(context: RegistrationCodeContext): string {
  const { prefix, includeYear, randomLength, separator } = REGISTRATION_CODE_FORMAT;

  const segments: string[] = [prefix];
  if (includeYear) segments.push(String(context.programYear));
  segments.push(randomSegment(randomLength));

  return segments.join(separator);
}

/** Loose shape check used when an applicant quotes their code for lookup. */
export function isPlausibleRegistrationCode(code: string): boolean {
  const normalised = normaliseRegistrationCode(code);
  return /^ZWCC-\d{4}-[A-Z0-9]{4,10}$/.test(normalised);
}

/** Codes are quoted verbally and typed with stray spaces — normalise on input. */
export function normaliseRegistrationCode(code: string): string {
  return code.trim().toUpperCase().replace(/\s+/g, '');
}
